spring.application.name=TODOListSpringBoot
spring.profiles.active=${APP_PROFILE:local}

server.address=0.0.0.0
server.port=8080

# --- Logging / Debugging ---
#logging.level.root=DEBUG
#logging.level.no.patreek.todolistspringboot=DEBUG
#logging.level.org.springframework.security=DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
#logging.level.org.springframework.web=DEBUG
#logging.level.org.springframework.web.filter=DEBUG
#logging.level.org.springframework.mail=DEBUG
